

export const AuditActions = {
  REGISTRATION_INITIATED: "REGISTRATION_INITIATED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
} as const;

export type AuditAction =  (typeof AuditActions)[keyof typeof AuditActions];